micronaut:
    application:
        name: storefront
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
tracing:
    jaeger:
        enabled: true
        sampler:
            probability: 1